name: test and release

on: push

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Install statik
        run: |
          GO111MODULE=off go get github.com/rakyll/statik

      - name: Build ui
        run: make build-ui

      - name: Build
        run: GIT_TAG_NAME=master-$GITHUB_RUN_NUMBER make build

      - name: Install gox
        run: |
          GO111MODULE=off go get github.com/mitchellh/gox

      - name: Install github-release
        run: |
          GO111MODULE=off go get github.com/aktau/github-release     

      - name: Build cross platform releases
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GOPATH: /home/runner/go
        run: |
          GIT_TAG_NAME=master-$GITHUB_RUN_NUMBER SHELL=/bin/bash ./build-release.sh

      - name: Upload latest cross platform releases to Github
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd ./target && for f in hoverfly_bundle*;do github-release upload  --user IGoRFonin --repo hoverfly --tag "${{github.ref_name}}" --name "$f" --file "$f"; done
