name: test and release

on: push

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.7

      - name: Install statik
        run: |
          GO111MODULE=off go get github.com/rakyll/statik

      - name: Build ui
        run: make build-ui

      - name: Build
        run: GIT_TAG_NAME=master-$GITHUB_RUN_NUMBER make build

      - name: Install gox
        run: |
          GO111MODULE=off go get github.com/mitchellh/gox

      - name: Publish to Registry
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker build -t igorfonin/hoverfly:${GITHUB_REF:10} .
          docker tag igorfonin/hoverfly:${GITHUB_REF:10} igorfonin/hoverfly:latest
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.GH_TOKEN }} ghrc.io
          docker push igorfonin/hoverfly:${GITHUB_REF:10}
          docker push igorfonin/hoverfly:latest
