name: release

on: push

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.7

      - name: Install statik
        run: |
          GO111MODULE=off go get github.com/rakyll/statik

      - name: Build ui
        run: make build-ui

      - name: Build
        run: GIT_TAG_NAME=master-$GITHUB_RUN_NUMBER make build

      - name: Install gox
        run: |
          GO111MODULE=off go get github.com/mitchellh/gox

      - name: Build cross platform releases
        if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/master')
        env:
          GOPATH: /home/runner/go
        run: |
          GIT_TAG_NAME=master-$GITHUB_RUN_NUMBER SHELL=/bin/bash ./build-release.sh

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: target/hoverfly_bundle_*

      - name: Publish to Registry
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_USER }}/hoverfly .
          docker tag ${{ secrets.DOCKER_IMAGE_USER }}/hoverfly ghcr.io/${{ secrets.DOCKER_IMAGE_USER }}/hoverfly:${GITHUB_REF:10}
          docker tag ${{ secrets.DOCKER_IMAGE_USER }}/hoverfly ghcr.io/${{ secrets.DOCKER_IMAGE_USER }}/hoverfly:latest
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.GH_TOKEN }} ghcr.io
          docker push ghcr.io/${{ secrets.DOCKER_IMAGE_USER }}/hoverfly:${GITHUB_REF:10}
          docker push ghcr.io/${{ secrets.DOCKER_IMAGE_USER }}/hoverfly:latest

      - name: Publish to Registry master tag
        if: startsWith(github.ref, 'refs/heads/master')
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_USER }}/hoverfly .
          docker tag ${{ secrets.DOCKER_IMAGE_USER }}/hoverfly ghcr.io/${{ secrets.DOCKER_IMAGE_USER }}/hoverfly:master
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.GH_TOKEN }} ghcr.io
          docker push ghcr.io/${{ secrets.DOCKER_IMAGE_USER }}/hoverfly:master
